interface Download { name: string; url: string; size: number; platform: string; arch: string; version: string; channel: string }
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function downloadPage(company: string, files: Download[], channel: string, version?: string, notes = '', userAgent = '') {
  const recommended = /Windows/i.test(userAgent) ? 'Windows' : /Macintosh|Mac OS X/i.test(userAgent) ? 'macOS' : '';
  const selected = files.filter(f => (!version || f.version === version) && (channel === 'beta' || f.channel === 'stable'));
  const seen = new Set<string>();
  const latest = selected.filter(f => { const key = `${f.platform}:${f.arch}`; if (seen.has(key)) return false; seen.add(key); return true; });
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>下载 Coding Access</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f6f8fc;color:#202b3d;font:15px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:820px;margin:64px auto;padding:0 24px}h1{font-size:30px;margin:0}p{color:#637089}nav{display:flex;gap:16px;margin:24px 0}a{color:#1768df}nav a{padding:6px 12px;text-decoration:none;border-radius:8px}nav a[aria-current=page]{background:#e7efff}article{background:white;border:1px solid #dce4f0;border-radius:12px;padding:22px 24px;margin:14px 0;display:flex;align-items:center;justify-content:space-between;gap:20px}h2{font-size:18px;margin:0}small{color:#637089}article p{margin:4px 0;overflow-wrap:anywhere}.download{white-space:nowrap;background:#1768df;color:white;border-radius:8px;padding:9px 20px;text-decoration:none}.badge{font-size:12px;color:#1768df;margin-left:10px}.notes{white-space:pre-wrap}.empty{padding:28px;background:white;border:1px solid #dce4f0;border-radius:12px}@media(max-width:560px){main{margin:32px auto;padding:0 16px}article{align-items:stretch;flex-direction:column}.download{text-align:center}}
  </style></head><body><main><h1>下载 Coding Access</h1><p>${escape(company)} · 团队模型客户端</p><nav><a href="/download?channel=stable" ${channel === 'stable' ? 'aria-current="page"' : ''}>稳定版</a><a href="/download?channel=beta" ${channel === 'beta' ? 'aria-current="page"' : ''}>测试版（含稳定版）</a></nav>
  ${version ? `<p>指定版本：${escape(version)} · <a href="/download?channel=${channel}">查看最新版</a></p>` : '<p>此链接会随管理员发布自动更新，无需重新索取下载地址。</p>'}
  ${latest.length ? latest.map(f => `<article><div><h2>${escape(f.platform)} · ${escape(f.arch === 'x64' && f.platform === 'macOS' ? 'Intel' : f.arch)}${recommended === f.platform ? '<span class="badge">当前系统</span>' : ''}</h2><p>${escape(f.version)} · ${(f.size / 1048576).toFixed(1)} MB</p><small>${escape(f.name)}</small></div><a class="download" href="${escape(f.url)}" download>下载安装包</a></article>`).join('') : `<div class="empty">${version ? '此版本未发布、已撤回或暂无可下载的安装包。' : '此通道尚未发布客户端，请稍后再试。'}</div>`}
  ${notes && latest.length ? `<h2>版本说明</h2><p class="notes">${escape(notes)}</p>` : ''}
  <p>仅列出已发布的平台；未列出的系统或架构暂无安装包。macOS 请按芯片选择 Apple Silicon 或 Intel。</p><p>下载无需登录。安装后使用公司账号登录；访问本服务需要公司内网或 VPN。</p></main></body></html>`;
}
