// Isolated local UI acceptance; no company service or real supplier requests.
import { chromium, expect } from '@playwright/test';
import { fixture } from '../tests/helpers.js';
import { createApp } from '../src/server/app.js';
import { resolve } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';
const f = await fixture(); const base = 'http://127.0.0.1:44517';
for (let i = 0; i < 90; i++) {
  const modelId = i % 2 ? f.model.id : 'past-model';
  const id = f.store.beginRequest(i % 3 ? f.employee.id : f.admin.id, modelId, 'claude-code');
  const at = Date.now() - (i % 6) * 86400_000 - i * 1000;
  f.store.db.prepare('UPDATE requests SET started_at=? WHERE id=?').run(at, id);
  f.store.attempt({ id: `attempt-${i}`, requestId: id, providerId: 'zhipu', keyId: 'z1', startedAt: at, status: 'success', input: 1000 + i * 40, output: 100, cached: 500 });
  f.store.finishRequest(id, 'success');
}
const { app } = await createApp({ ...f, publicUrl: base, webRoot: resolve('dist/web'), updatesRoot: resolve('.local/product-ui-artifacts'), gateway: { fetch: async () => { throw new Error('Real inference disabled'); } } });
let polls = 0; app.addHook('onResponse', async r => { if (r.url === '/api/admin/keys') polls++; });
await app.listen({ host: '127.0.0.1', port: 44517 });
const browser = await chromium.launch({ channel: 'chrome' }); mkdirSync('output/verification', { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } }); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(base); await page.getByPlaceholder('输入账号').fill('admin'); await page.getByLabel('密码', { exact: true }).fill('TestPassword123!'); await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('heading', { name: '工作台', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '用量统计', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Token 用量趋势' })).toBeVisible();
  await page.screenshot({ animations: 'disabled', path: 'output/verification/product-statistics.png', fullPage: true });
  await page.getByRole('tab', { name: '模型排行' }).click(); await expect(page.getByRole('cell', { name: 'GLM Test', exact: true })).toBeVisible();
  await page.screenshot({ animations: 'disabled', path: 'output/verification/product-model-ranking.png', fullPage: true });
  await page.getByRole('tab', { name: '成员排行' }).click(); await expect(page.getByRole('cell', { name: '开发同事', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: '调用明细' }).click(); await expect(page.getByText('共 90 条', { exact: false })).toBeVisible();
  const downloaded = page.waitForEvent('download'); await page.getByRole('button', { name: '导出当前统计' }).click(); const download = await downloaded; await download.saveAs('output/verification/product-usage.csv');
  await page.getByRole('button', { name: '下一页' }).click(); await expect(page.getByText('第 2 页', { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 900, height: 700 }); await page.screenshot({ animations: 'disabled', path: 'output/verification/product-statistics-narrow.png', fullPage: true });
  await page.getByRole('button', { name: '资源池', exact: true }).click(); const before = polls; await expect.poll(() => polls, { timeout: 6000 }).toBeGreaterThan(before + 1);
  await page.evaluate("Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange'));"); const paused = polls; await page.waitForTimeout(2500); expect(polls).toBe(paused);
  await page.evaluate("Object.defineProperty(document, 'hidden', { configurable: true, get: () => false }); document.dispatchEvent(new Event('visibilitychange'));"); await expect.poll(() => polls, { timeout: 6000 }).toBeGreaterThan(paused);
  await page.getByRole('button', { name: '设置与维护', exact: true }).click(); await expect(page.getByText('配置备份与恢复', { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ animations: 'disabled', path: 'output/verification/server-maintenance-simple.png', fullPage: true });
  await page.getByRole('button', { name: '客户端发布', exact: true }).click();
  await expect(page.getByRole('heading', { name: '客户端发布', exact: true })).toBeVisible();
  // Repair an old Windows publication through the actual form without replacing its installer.
  const oldFile = (await app.inject({ method: 'POST', url: '/api/admin/client-artifacts?platform=windows-x86_64&kind=installer&name=Coding-Access-0.2.0-beta.6-win-x64-setup.exe', headers: { cookie: `aca_session=${f.adminSession}`, 'content-type': 'application/octet-stream' }, payload: Buffer.from('fixture-package') })).json();
  const oldRelease = (await app.inject({ method: 'POST', url: '/api/admin/client-releases', headers: { cookie: `aca_session=${f.adminSession}` }, payload: { version: '0.2.0-beta.6', channel: 'beta', notes: 'Legacy updater repair', minServerVersion: '0.1.16', artifactIds: [oldFile.id] } })).json();
  f.store.db.prepare('UPDATE client_releases SET data=? WHERE id=?').run(JSON.stringify({ ...oldRelease, published: true }), oldRelease.id);
  await page.getByRole('button', { name: '刷新客户端版本' }).click();
  await page.getByRole('button', { name: '补全更新文件' }).click();
  await page.getByLabel('Windows x64 应用内更新包', { exact: true }).setInputFiles({ name: oldFile.name, mimeType: 'application/octet-stream', buffer: Buffer.from('fixture-package') });
  await page.getByLabel('Windows x64 更新签名', { exact: true }).setInputFiles({ name: 'win.sig', mimeType: 'text/plain', buffer: Buffer.from('YWJj') });
  await page.getByRole('button', { name: '上传并检查', exact: true }).click();
  await page.getByRole('button', { name: '补全并保持发布', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('更新文件已补全');
  const repairedFeed = await page.request.get(base + '/api/client-updater/beta/windows-x86_64/0.2.0-beta.5');
  expect((await repairedFeed.json()).version).toBe('0.2.0-beta.6');
  await page.getByRole('button', { name: '发布新版本', exact: true }).click();
  await page.getByLabel('客户端版本', { exact: true }).fill('0.2.0-beta.7'); await page.getByLabel('更新说明').fill('简化设置与更新界面，支持应用内升级。');
  await page.screenshot({ animations: 'disabled', path: 'output/verification/publish-version.png' });
  await page.getByRole('button', { name: '下一步：选择文件' }).click();
  await page.getByRole('button', { name: '上传并检查', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('请选择完整安装包');
  const file = (name: string) => ({ name, mimeType: 'application/octet-stream', buffer: Buffer.from('fixture-package') });
  await page.getByLabel('macOS Apple Silicon 完整安装包', { exact: true }).setInputFiles(file('Coding-Access-0.2.0-beta.7-mac-arm64.zip'));
  await page.getByLabel('macOS Apple Silicon 应用内更新包', { exact: true }).setInputFiles(file('Coding-Access-0.2.0-beta.7-mac-arm64.app.tar.gz'));
  await page.getByLabel('macOS Apple Silicon 更新签名', { exact: true }).setInputFiles({ ...file('mac.sig'), buffer: Buffer.from('YWJj') });
  await page.getByLabel('Windows x64 完整安装包', { exact: true }).setInputFiles(file('Coding-Access-0.2.0-beta.7-win-x64-setup.exe'));
  await page.getByLabel('Windows x64 更新签名', { exact: true }).setInputFiles({ ...file('win.sig'), buffer: Buffer.from('YWJj') });
  await page.screenshot({ animations: 'disabled', path: 'output/verification/publish-files.png' });
  await page.getByRole('button', { name: '上传并检查', exact: true }).click();
  await expect(page.getByRole('button', { name: '确认发布', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 900, height: 650 });
  const publishBox = await page.getByRole('button', { name: '确认发布', exact: true }).boundingBox();
  expect(publishBox!.y + publishBox!.height).toBeLessThan(650);
  await page.screenshot({ animations: 'disabled', path: 'output/verification/publish-confirm.png' });
  await page.getByRole('button', { name: '确认发布', exact: true }).click();
  await expect(page.getByRole('cell', { name: '已发布', exact: true })).toHaveCount(2);
  const feed = await page.request.get(base + '/api/client-updater/beta/windows-x86_64/0.2.0-beta.5');
  expect((await feed.json()).version).toBe('0.2.0-beta.7');
  await page.setViewportSize({ width: 1440, height: 900 }); await page.screenshot({ animations: 'disabled', path: 'output/verification/publish-list.png', fullPage: true });
  expect(errors).toEqual([]); writeFileSync('output/verification/product-ui.json', JSON.stringify({ passed: true, checks: ['overview retained', 'token trend', 'model ranking', 'member ranking', '90-row export', 'pagination', 'resource polling and hidden pause', 'release management'], errors }, null, 2));
} finally { await browser.close(); await app.close(); f.store.close(); }
